language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- cd test

install:
- sudo apt-get install -qq g++-5
- export CXX="g++-5"

script: make && ../scripts/run_tests.sh